### ISSUE TITLE
Aligning the logos correctly

### ISSUE THREAD

**Issue by mashiromashi** [mashiromashi/portfolio#2]
Please help me align the logos correctly as I'm not that familiar with css

**Comment by ogandose** [comment]
I would like to try this 🙂

**Comment by ogandose** [comment]
How do you want them aligned exactly? 🙂

**Comment by mashiromashi** [comment]
![image](https://user-images.githubusercontent.com/13332659/67001781-7bc03980-f100-11e9-9957-db1f497de666.png)

as you can see in this image, the images are very far apart. I just want them to be a little bit compact and look a bit neat and tidy. I myself is learning how to use css well so please help me out if possible. 

I use flex layout to align currently

**Comment by mashiromashi** [comment]
Closing this issue as this has been implemented in #4
